---
title: Glenna DeRoy
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-minimal
description: Product at CommonBond. Feminist. Traveler. Baseball fan. Coffee junkie.
gems:
- jemoji
